
export const ProductData = [
    {
      "id": 1,
      "name": "Sony WH-1000XM5 Wireless Noise-Canceling Headphones",
      "image": "https://m.media-amazon.com/images/I/51aXvjzcukL._SX522_.jpg",
      "category": "Headphones",
      "brand": "Sony",
      "price": { "currency": "INR", "amount": 29049.17 },
      "availability": "In Stock",
      "rating": 4.8,
      "reviews": 1298,
      "description": "Industry-leading noise-canceling headphones with superior sound."
    },
    {
      "id": 2,
      "name": "Apple MacBook Pro 16-inch (2024)",
      "image": "https://m.media-amazon.com/images/I/618d5bS2lUL._AC_UY327_FMwebp_QL65_.jpg",
      "category": "Laptops",
      "brand": "Apple",
      "price": { "currency": "INR", "amount": 207498.17 },
      "availability": "In Stock",
      "rating": 4.9,
      "reviews": 876,
      "description": "Powerful MacBook Pro with M2 chip and stunning display."
    },
    {
      "id": 3,
      "name": "Samsung Galaxy S24 Ultra 5G",
      "image": "https://m.media-amazon.com/images/I/71RVuBs3q9L._AC_UY327_FMwebp_QL65_.jpg",
      "category": "Smartphones",
      "brand": "Samsung",
      "price": { "currency": "INR", "amount": 99599.17 },
      "availability": "Pre-Order",
      "rating": 4.7,
      "reviews": 543,
      "description": "Latest 5G smartphone with 108MP camera and 120Hz AMOLED display."
    },
    {
      "id": 4,
      "name": "LG OLED 65-inch 4K Smart TV",
      "image": "https://m.media-amazon.com/images/I/81zlF3XIJ3L._AC_UY327_FMwebp_QL65_.jpg",
      "category": "Televisions",
      "brand": "LG",
      "price": { "currency": "INR", "amount": 165998.17 },
      "availability": "In Stock",
      "rating": 4.6,
      "reviews": 754,
      "description": "65-inch 4K OLED TV with Dolby Vision and AI-powered upscaling."
    },
    {
      "id": 5,
      "name": "Dell XPS 13 Laptop (2024)",
      "image": "https://m.media-amazon.com/images/I/51zY-mOR7kL._AC_UY327_FMwebp_QL65_.jpg",
      "category": "Laptops",
      "brand": "Dell",
      "price": { "currency": "INR", "amount": 124498.17 },
      "availability": "In Stock",
      "rating": 4.5,
      "reviews": 653,
      "description": "Ultra-thin Dell XPS with 11th Gen Intel Core i7 processor."
    },
    {
      "id": 6,
      "name": "Bose SoundLink Revolve+ II Portable Speaker",
      "image": "https://m.media-amazon.com/images/I/71UOdiQnBCL._AC_UY327_FMwebp_QL65_.jpg",
      "category": "Speakers",
      "brand": "Bose",
      "price": { "currency": "INR", "amount": 27349.17 },
      "availability": "In Stock",
      "rating": 4.8,
      "reviews": 2345,
      "description": "Powerful 360° sound speaker with Bluetooth connectivity."
    },
    {
      "id": 7,
      "name": "Sony PlayStation 5",
      "image": "https://m.media-amazon.com/images/I/51ljnEaW0pL._AC_UY327_FMwebp_QL65_.jpg",
      "category": "Gaming Consoles",
      "brand": "Sony",
      "price": { "currency": "INR", "amount": 41499.17 },
      "availability": "In Stock",
      "rating": 4.9,
      "reviews": 8700,
      "description": "The latest gaming console with ultra-fast SSD and 4K gaming."
    },
    {
      "id": 8,
      "name": "Microsoft Xbox Series X",
      "image": "https://m.media-amazon.com/images/I/71NBQ2a52CL._AC_UY327_FMwebp_QL65_.jpg",
      "category": "Gaming Consoles",
      "brand": "Microsoft",
      "price": { "currency": "INR", "amount": 41499.17 },
      "availability": "In Stock",
      "rating": 4.7,
      "reviews": 6850,
      "description": "Powerful next-gen console with 12 teraflops of performance."
    },
    {
      "id": 9,
      "name": "Canon EOS R5 Mirrorless Camera",
      "image": "https://m.media-amazon.com/images/I/719z+CUIFVL._AC_UY327_FMwebp_QL65_.jpg",
      "category": "Cameras",
      "brand": "Canon",
      "price": { "currency": "INR", "amount": 323699.17 },
      "availability": "In Stock",
      "rating": 4.8,
      "reviews": 945,
      "description": "Professional-grade mirrorless camera with 8K video recording."
    },
    {
      "id": 10,
      "name": "Apple iPad Pro 12.9-inch (2024)",
      "image": "https://m.media-amazon.com/images/I/71qV9xzdxzL._AC_UY327_FMwebp_QL65_.jpg",
      "category": "Tablets",
      "brand": "Apple",
      "price": { "currency": "INR", "amount": 91249.17 },
      "availability": "In Stock",
      "rating": 4.9,
      "reviews": 3220,
      "description": "Large-screen iPad Pro with M2 chip and 120Hz display."
    },
    {
      "id": 11,
      "name": "Samsung Galaxy Tab S8+",
      "image": "https://m.media-amazon.com/images/I/81elHEv1QrL._AC_UY327_FMwebp_QL65_.jpg",
      "category": "Tablets",
      "brand": "Samsung",
      "price": { "currency": "INR", "amount": 74699.17 },
      "availability": "In Stock",
      "rating": 4.6,
      "reviews": 1500,
      "description": "High-performance tablet with AMOLED display and S Pen support."
    },
    {
      "id": 12,
      "name": "Fitbit Versa 4 Fitness Smartwatch",
      "image": "https://m.media-amazon.com/images/I/61GD5fmd0XL._AC_UY327_FMwebp_QL65_.jpg",
      "category": "Wearables",
      "brand": "Fitbit",
      "price": { "currency": "INR", "amount": 20749.17 },
      "availability": "In Stock",
      "rating": 4.5,
      "reviews": 1250,
      "description": "Smartwatch with built-in GPS and health tracking features."
    },
    {
      "id": 13,
      "name": "Apple Watch Series 9",
      "image": "https://m.media-amazon.com/images/I/81KftY1Jb6L._AC_UY327_FMwebp_QL65_.jpg",
      "category": "Wearables",
      "brand": "Apple",
      "price": { "currency": "INR", "amount": 33199.17 },
      "availability": "In Stock",
      "rating": 4.8,
      "reviews": 5210,
      "description": "Advanced health tracking smartwatch with ECG and blood oxygen monitoring."
    },
    {
      "id": 14,
      "name": "Logitech MX Master 3 Wireless Mouse",
      "image": "https://m.media-amazon.com/images/I/61VBfFUa6xL._AC_UY327_FMwebp_QL65_.jpg",
      "category": "Accessories",
      "brand": "Logitech",
      "price": { "currency": "INR", "amount": 8299.17 },
      "availability": "In Stock",
      "rating": 4.7,
      "reviews": 3400,
      "description": "Ergonomic wireless mouse with hyper-fast scrolling and programmable buttons."
    },
    {
      "id": 15,
      "name": "Anker PowerCore 10000 Portable Charger",
      "image": "https://m.media-amazon.com/images/I/71iMZQaT8DL._AC_UY327_FMwebp_QL65_.jpg",
      "category": "Accessories",
      "brand": "Anker",
      "price": { "currency": "INR", "amount": 2079.17 },
      "availability": "In Stock",
      "rating": 4.7,
      "reviews": 5400,
      "description": "Compact and portable power bank with 10000mAh capacity."
    },
      {
        "id": 16,
        "name": "Dyson V15 Detect Cordless Vacuum Cleaner",
        "image":"https://m.media-amazon.com/images/I/71ziuQZWCjL._AC_UY327_FMwebp_QL65_.jpg",
        "category": "Home Appliances",
        "brand": "Dyson",
      "price": { "currency": "INR", "amount":58815.30 },
        "availability": "In Stock",
        "rating": 4.9,
        "reviews": 3200,
        "description": "Powerful cordless vacuum cleaner with laser detection technology."
      },
      {
        "id": 17,
        "name": "Google Nest Hub (2nd Gen)",
         "image":"https://m.media-amazon.com/images/I/61p+HaIkPCL._AC_UY327_FMwebp_QL65_.jpg",
        "category": "Smart Home",
        "brand": "Google",
        "price": { "currency": "INR", "amount":8404.85 },
        "availability": "In Stock",
        "rating": 4.6,
        "reviews": 540,
        "description": "Smart display with Google Assistant, sleep tracking, and smart home controls."
      },
      {
        "id": 18,
        "name": "Amazon Echo (4th Gen)",
        "image":"https://m.media-amazon.com/images/I/61dgl2srHDL._AC_UY327_FMwebp_QL65_.jpg",
        "category": "Smart Home",
        "brand": "Amazon",
       "price": { "currency": "INR", "amount":8404.85 },

        "availability": "In Stock",
        "rating": 4.7,
        "reviews": 2850,
        "description": "Smart speaker with Alexa, premium sound, and smart home integration."
      },
      {
        "id": 19,
        "name": "Razer Blade 15 Advanced Gaming Laptop",
         "image":"https://m.media-amazon.com/images/I/61ZW4kl+fBL._AC_UY327_FMwebp_QL65_.jpg",
        "category": "Laptops",
        "brand": "Razer",
        "price": { "currency": "INR", "amount": 235344.92 },
        "availability": "In Stock",
        "rating": 4.8,
        "reviews": 1298,
        "description": "High-performance gaming laptop with NVIDIA RTX 3080 GPU."
      },
      {
        "id": 20,
        "name": "HP Spectre x360 14-inch Convertible Laptop",
         "image":"https://m.media-amazon.com/images/I/61HaZEds5KL._AC_UY327_FMwebp_QL65_.jpg",
        "category": "Laptops",
        "brand": "HP",
        "price": { "currency": "INR", "amount":134490.15},
        "availability": "In Stock",
        "rating": 4.7,
        "reviews": 685,
        "description": "Convertible laptop with 11th Gen Intel Core i7 and 4K display."
      },
      {
        "id": 21,
        "name": "Sony Alpha 7 IV Full-Frame Camera",
         "image":"https://m.media-amazon.com/images/I/81Tr3Jo8DvL._AC_UY327_FMwebp_QL65_.jpg",
        "category": "Cameras",
        "brand": "Sony",
        "price": { "currency": "INR", "amount": 210127.78},
        "availability": "In Stock",
        "rating": 4.9,
        "reviews": 456,
        "description": "Full-frame mirrorless camera with 33MP sensor and 4K 60p video."
      },
      {
        "id": 22,
        "name": "Google Pixel 8 Pro 5G",
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/e/f/m/-original-imagtwh5rbhf7ngh.jpeg?q=70",
        "category": "Smartphones",
        "brand": "Google",
       "price": { "currency": "INR", "amount":134490.15},
        "availability": "In Stock",
        "rating": 4.1,
        "reviews": 980,
        "description": "Google's flagship smartphone with advanced AI features and a 50MP camera."
      },
      {
        "id": 23,
        "name": "OnePlus 11 5G",
        "image":"https://m.media-amazon.com/images/I/61amb0CfMGL._SX679_.jpg",
        "category": "Smartphones",
        "brand": "OnePlus",
        "price": { "currency": "INR", "amount": 75641.69 },
        "availability": "In Stock",
        "rating": 4.7,
        "reviews": 450,
        "description": "High-performance 5G smartphone with a 120Hz display and fast charging."
      },
      {
        "id": 24,
        "name": "Sony WH-XB910N Wireless Extra Bass Headphones",
        "image":"https://m.media-amazon.com/images/I/51KGPDttQhL._AC_SR155,154_QL70_.jpg",
        "category": "Headphones",
        "brand": "Sony",
        "price": { "currency": "INR", "amount":16808.61},
        "availability": "In Stock",
        "rating": 4.6,
        "reviews": 1820,
        "description": "Noise-canceling wireless headphones with extra bass for deep sound."
      },
      {
        "id": 25,
        "name": "Asus ROG Phone 6 Pro",
        "image":"https://m.media-amazon.com/images/I/41PfgdPzB2L._AC_UL480_FMwebp_QL65_.jpg",
        "category": "Smartphones",
        "brand": "Asus",
        "price": { "currency": "INR", "amount": 92458.79 },
        "availability": "In Stock",
        "rating": 4.8,
        "reviews": 780,
        "description": "Gaming smartphone with Snapdragon 8 Gen 1 chip and 165Hz AMOLED display."
      },
      {
        "id": 26,
        "name": "JBL Charge 5 Portable Bluetooth Speaker",
        "image":"https://m.media-amazon.com/images/I/71N8si9jomL._AC_UY327_FMwebp_QL65_.jpg",
        "category": "Speakers",
        "brand": "JBL",
        "price": { "currency": "INR", "amount":15128.91},
        "availability": "In Stock",
        "rating": 4.7,
        "reviews": 2340,
        "description": "Waterproof Bluetooth speaker with powerful sound and 20 hours of playtime."
      }
      
    ]
  
  